# Generated by Django 3.0.2 on 2020-01-30 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_remove_supplier_bill'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier', verbose_name='Supplier'),
        ),
    ]
