# Generated by Django 3.0.2 on 2020-02-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_bill_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='stock',
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
    ]
