# Generated by Django 3.0.2 on 2020-01-29 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('company', models.CharField(max_length=50, verbose_name='Company')),
                ('address', models.TextField(verbose_name='Address')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Bill', verbose_name='Bills')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
    ]
