# Generated by Django 3.0.2 on 2020-01-29 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('mfd', models.DateField(verbose_name='Manufactured on')),
                ('exp', models.DateField(verbose_name='Expires on')),
                ('placed_at', models.CharField(blank=True, max_length=40, null=True, verbose_name='Placed at')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Bill', verbose_name='Bill')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meds', to='customer.Customer', verbose_name='')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
            },
        ),
    ]
