# Generated by Django 3.0.2 on 2020-02-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_auto_20200205_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Content'),
        ),
    ]
