# Generated by Django 3.0.2 on 2020-02-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_auto_20200206_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='content',
        ),
        migrations.AddField(
            model_name='medicine',
            name='Description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='contains',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Contains'),
        ),
    ]
