# Generated by Django 3.0.2 on 2020-02-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_auto_20200206_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='mfd_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Manufactured by'),
        ),
    ]
